services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=kdao2003
      - MONGO_INITDB_ROOT_PASSWORD=kdao2003

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=kdao2003
      - ME_CONFIG_MONGODB_ADMINPASSWORD=kdao2003
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=kdao2003
      - ME_CONFIG_BASICAUTH_PASSWORD=kdao2003
volumes:
  mongo: {}
